// src/domElements.js
export function getDOMElements() {
    return {
        publicationsListOl: document.getElementById('publications-list-ol'),
        xCoordInput: document.getElementById('xCoord'),
        yCoordInput: document.getElementById('yCoord'),
        zCoordInput: document.getElementById('zCoord'),
        yearInput: document.getElementById('yearInput'),
        authorTextInput: document.getElementById('authorText'),
        shortTitleTextInput: document.getElementById('shortTitleText'),
        timeSlider: document.getElementById('timeSlider'),
        timeSliderValueSpan: document.getElementById('timeSliderValue'),
        messageBox: document.getElementById('message-box'),
        addEditButton: document.getElementById('addEditButton'),
        axesVisContainer: document.getElementById('axes-visualization'),
        mainContentArea: document.getElementById('main-content'),
        controlsDiv: document.getElementById('controls'),
        ngoCheckbox: document.getElementById('ngoCheckbox'),
        governmentCheckbox: document.getElementById('governmentCheckbox'),
        academiaCheckbox: document.getElementById('academiaCheckbox'),
        importButton: document.getElementById('importButton'),
        exportButton: document.getElementById('exportButton'),
        csvFileInput: document.getElementById('csvFileInput'),
        filterNgoCheckbox: document.getElementById('filterNgoCheckbox'),
        filterGovernmentCheckbox: document.getElementById('filterGovernmentCheckbox'),
        filterAcademiaCheckbox: document.getElementById('filterAcademiaCheckbox'),
        toggleControlsButton: document.getElementById('toggle-controls-button'),
        xAxisBar: document.querySelector('#axes-visualization .x-axis'),
        yAxisBar: document.querySelector('#axes-visualization .y-axis'),
        zAxisBar: document.querySelector('#axes-visualization .z-axis'),
        axesSelectedItemText: document.getElementById('axes-selected-item'),
        toggleSortButton: document.getElementById('toggleSortButton'),
        sortOptionsBar: document.getElementById('sortOptionsBar'),
        authorAsc: document.getElementById('authorAsc'),
        authorDesc: document.getElementById('authorDesc'),
        titleAsc: document.getElementById('titleAsc'),
        titleDesc: document.getElementById('titleDesc'),
        yearAsc: document.getElementById('yearAsc'),
        yearDesc: document.getElementById('yearDesc')
    };
}